# Generated by Django 3.1.2 on 2021-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211201_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
